FROM amazonlinux:2
RUN yum -y install autoconf automake binutils gcc gcc-c++ gettext libtool make patch pkgconfig redhat-rpm-config rpm-build
RUN yum -y install clang openssl openssl11-devel
RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN yum -y install cargo

ARG PLATFORM
WORKDIR /root/rpmbuild/BUILD
COPY . .
RUN rpm -qa | grep openssl
RUN make redhat

FROM stage AS export
ARG PLATFORM
COPY --from=stage /root/rpmbuild/RPMS/*/*.rpm ./${PLATFORM}/
