FROM alpine:edge as stage
ARG RUST_TRIPLET

RUN apk update
RUN apk add curl
RUN apk add build-base
RUN apk add bash
RUN apk add file
RUN apk add rust
RUN apk add make
RUN apk add clang

COPY . .
RUN make one
RUN ls -lahR

FROM scratch AS export
ARG PLATFORM
COPY --from=stage * ./${PLATFORM}/
