FROM alpine:edge as stage
ARG RUST_TRIPLET

RUN apk update
RUN apk add curl
RUN apk add bash
RUN apk add file
RUN apk add rust
RUN apk add cargo
RUN apk add make
RUN apk add cmake
RUN apk add clang
RUN apk add openssl-dev
RUN apk add linux-headers
RUN apk add libstdc++
RUN apk add build-base
RUN apk add libssl

COPY . .
RUN ZT_STATIC=1 make one
RUN ls -lah

FROM scratch AS export
ARG PLATFORM
COPY --from=stage zerotier-one ./${PLATFORM}/
