FROM registry.access.redhat.com/ubi8/ubi as stage
RUN yum -y update
RUN yum -y install autoconf automake binutils gcc gcc-c++ gettext libtool make patch pkgconfig redhat-rpm-config rpm-build
RUN yum -y install clang openssl-libs openssl-devel
RUN yum -y install systemd
COPY ./ci/rust.sh .
RUN ./rust.sh ${RUST_TRIPLET}

ARG PLATFORM
WORKDIR /root/rpmbuild/BUILD
COPY . .
RUN make redhat

FROM scratch AS export
ARG PLATFORM
COPY --from=stage /root/rpmbuild/RPMS/*/*.rpm ./${PLATFORM}/
