FROM alpine:edge as stage
ARG RUST_TRIPLET

RUN apk update
RUN apk add curl
RUN apk add clang
RUN apk add bash
RUN apk add file
RUN apk add rust
RUN apk add make
RUN apk add make
RUN apk add musl
RUN apk add musl-dev
RUN apk add libstdc++
RUN apk add libc-dev

COPY . .
RUN make one
RUN ls -lahR

FROM scratch AS export
ARG PLATFORM
COPY --from=stage * ./${PLATFORM}/
