FROM fedora:37 as stage
ARG RUST_TRIPLET
RUN yum -y install autoconf automake binutils gettext libtool make patch pkgconfig redhat-rpm-config rpm-build
RUN yum -y install clang clang-libs openssl1.1 openssl1.1-devel
RUN yum -y install systemd
COPY ./ci/rust.sh .
RUN ./rust.sh ${RUST_TRIPLET}

ARG PLATFORM
WORKDIR /root/rpmbuild/BUILD
COPY . .
RUN /usr/bin/clang --version
RUN make redhat

FROM scratch AS export
ARG PLATFORM
COPY --from=stage /root/rpmbuild/RPMS/*/*.rpm ./${PLATFORM}/
